version: '3.4'

services:
  httpCachingProxy:
    build:
      context: ./src
      dockerfile: ./src/Dockerfile
      volumes:
      - "./src:/src"
      - "./logs:/var/log/erss"
      ports:
      - "12345:12345"
